# Generated by Django 4.2.7 on 2024-05-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_remove_product_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_detail_url',
            field=models.TextField(null=True),
        ),
    ]
