# Generated by Django 4.2.7 on 2024-05-24 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address1',
            new_name='shipping_address1',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address2',
            new_name='shipping_address2',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='shipping_city',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='dictrict',
            new_name='shipping_dictrict',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='email',
            new_name='shipping_email',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='fullName',
            new_name='shipping_fullName',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='ward',
            new_name='shipping_ward',
        ),
    ]
