# Generated by Django 4.2.7 on 2024-05-25 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_app', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order_id',
        ),
    ]
