# Generated by Django 4.2.7 on 2024-05-25 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_app', '0006_remove_shippingaddress_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shippingAddress',
        ),
    ]
