# Generated by Django 4.2.7 on 2024-05-25 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout_app', '0012_initial'),
        ('order_app', '0014_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order_app.order'),
        ),
    ]
