# Generated by Django 4.2.7 on 2024-05-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout_app', '0014_delete_shippingaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='shippingAddress',
            fields=[
                ('shipping_id', models.AutoField(primary_key=True, serialize=False)),
                ('shipping_fullname', models.CharField(max_length=255, null=True)),
                ('shipping_email', models.CharField(max_length=255, null=True)),
                ('shipping_address1', models.CharField(max_length=255, null=True)),
                ('shipping_address2', models.CharField(max_length=255, null=True)),
                ('shipping_ward', models.CharField(max_length=255, null=True)),
                ('shipping_district', models.CharField(max_length=255, null=True)),
                ('shipping_city', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Shipping Address',
            },
        ),
    ]
