# Generated by Django 4.2.7 on 2024-05-25 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_app', '0006_remove_shippingaddress_order_id'),
        ('order_app', '0002_rename_customer_order_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
