# Generated by Django 4.2.7 on 2024-05-25 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
