# Generated by Django 4.2.7 on 2024-05-25 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
