# Generated by Django 4.2.7 on 2024-05-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0008_orderdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='total',
        ),
    ]
