# Generated by Django 4.2.7 on 2024-05-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_app', '0009_delete_shippingaddress'),
        ('order_app', '0009_rename_total_amount_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
