# Generated by Django 4.2.7 on 2024-05-25 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_app', '0014_delete_shippingaddress'),
        ('order_app', '0015_alter_orderdetail_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
