# Generated by Django 4.2.7 on 2024-06-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0017_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
