# Generated by Django 4.2.7 on 2024-06-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0018_alter_orderdetail_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='point',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
