# Generated by Django 4.2.7 on 2024-06-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0019_alter_order_point_alter_order_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='order',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='product',
            new_name='product_id',
        ),
    ]
