# Generated by Django 4.2.7 on 2024-06-04 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0020_rename_order_orderdetail_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='product_id',
            new_name='product',
        ),
    ]
