# Generated by Django 4.2.7 on 2024-05-01 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_userprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
