# Generated by Django 4.2.7 on 2024-06-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0007_userprofile_old_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bank_card_info',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
