# Generated by Django 4.2.7 on 2024-06-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0008_userprofile_bank_card_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bank_card_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
