# Generated by Django 4.2.7 on 2024-06-04 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0009_alter_userprofile_bank_card_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bank_card_info',
        ),
    ]
